package/zabbix: netsnmp needs mib
netsnmp support needs mib to avoid the following build failure raised
since the addition of the package in commit
42382a171277ead59e365f5920e757f01c04ac77:

checks_snmp.c: In function ‘zbx_snmp_get_octet_string’:
checks_snmp.c:694:35: error: invalid use of undefined type ‘struct tree’
  694 |  hint = (NULL != subtree ? subtree->hint : NULL);
      |                                   ^~

Fixes:
 - No autobuilder failures (yet)

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 77f9d2d6a6fc4a6485acd7b5f1970b638764c1fa)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>