package/pango: fix empty-body
Fix the following build failure raised since bump to version 1.50.5 in
commit 68b0efbae49a42d0e14d6040e5e7e573d382ff75:

../utils/viewer-cairo.c: In function 'cairo_vector_view_create':
../utils/viewer-cairo.c:228:5: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
     ;
     ^

Fixes:
 - http://autobuild.buildroot.org/results/dee3d631474f83b345f22eb26c59a305c32258f8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 43991ac5e0e6cdb4aa03ed7011243aa0f473fd56)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>