package/zynaddsubfx: fix atomic linking
Fix the following build failure raised since the addition of the package
in commit 18a863063735e2c658fa6947a4e540e9dda6c431:

/home/giuliobenetti/autobuild/run/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/riscv64-buildroot-linux-musl/10.3.0/../../../../riscv64-buildroot-linux-musl/bin/ld: libzynaddsubfx_core.a(Master.cpp.o): in function `.L1880':
Master.cpp:(.text+0x7cc0): undefined reference to `__atomic_exchange_1'

Fixes:
 - http://autobuild.buildroot.org/results/91b5959ca0eb136c1609462e71d109ff09cca5e5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>
(cherry picked from commit ba7319a06e1b98524fde1384dc570a7f34870881)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>