package/bluez5_utils: hid and hog needs headers >= 3.18
Fix the following build failure with hid and hog raised since their
addition in commit fb9fc969d91f69851b4c70dba512b607e52bda7b and
https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=9b58288693680b021e5dcbc6f8bea80b5be89311
https://git.kernel.org/pub/scm/bluetooth/bluez.git/commit/?id=646db71713b05d50b2b0c421da34e80ed4c54fbd
because UHID_GET_REPORT is only available since kernel 3.18 and
https://github.com/torvalds/linux/commit/fa71f32b5de2be1644ee671ddbe211d79be7847f:

profiles/input/device.c: In function 'uhid_send_get_report_reply':
profiles/input/device.c:222:24: error: 'union <anonymous>' has no member named 'get_report_reply'
  if (size > sizeof(ev.u.get_report_reply.data))
                        ^
profiles/input/device.c:223:21: error: 'union <anonymous>' has no member named 'get_report_reply'
   size = sizeof(ev.u.get_report_reply.data);
                     ^
profiles/input/device.c:231:12: error: 'UHID_GET_REPORT_REPLY' undeclared (first use in this function)
  ev.type = UHID_GET_REPORT_REPLY;
            ^

Fixes:
 - http://autobuild.buildroot.org/results/1db406eac7620e3f76d997414eb7af7d2ac6cfe6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 328516a5add9e6f260d3a8e0d372c474ae30b2c1)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>