laird: package/mtd: add patch to fix host build error with gcc 5.1
host-mtd build fails with gcc 5.1:
  error: redefinition of ‘hashtable_iterator_key’
  error: redefinition of ‘hashtable_iterator_value’

Indeed, both functions are defined twice - once in the header and once in the
source file. This is permitted in C11 (and maybe in C99).

Add a patch sent to upstream:
https://patchwork.ozlabs.org/patch/467254/

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Tested-by: Doug Kehn <rdkehn@yahoo.com>
Tested-by: Romain Naour <romain.naour@openwide.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>