package/trousers: fix build with libressl >= 2.7.0
Fix the following build failure with libressl >= 2.7.0:

crypto/openssl/rsa.c:43:1: error: static declaration of 'RSA_set0_key' follows non-static declaration
   43 | RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d)
      | ^~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/607131255453da2dc0dab20a24264b3e74001525

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 2d4a9308d7b16e4fd613a9070a97c9effa055b4b)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>