package/tvheadend: fix build with libressl
Fix the following build failure with libressl:

utils.c:(.text+0x1614): undefined reference to `EVP_sha512_256'

Fixes:
 - http://autobuild.buildroot.org/results/cb18f6533806f3729f9718bdcc719384be375b66

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit 04164b81e76e29fb9482245e808b46af2aa67bc6)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>