package/nodejs/0.10.x: add patch to fix musl build error
The musl C library does not understand the feature test macro __USE_MISC and so
libuv (built-in dependency of nodejs) does not use the correct struct stat
definition for musl:
	error: ‘uv_statbuf_t’ has no member named ‘st_ctimensec’
	error: ‘uv_statbuf_t’ has no member named ‘st_mtimensec’

The macro __USE_MISC is defined by glibc if _BSD_SOURCE or _SVID_SOURCE is
defined.

The libuv build system enables the feature test macro _GNU_SOURCE for linux
builds.

Since glibc 2.19, defining _GNU_SOURCE also has the effect of implicitly
defining _DEFAULT_SOURCE - the replacement for _BSD_SOURCE and _SVID_SOURCE.

In glibc versions before 2.20, defining _GNU_SOURCE also had the effect of
implicitly defining _BSD_SOURCE and _SVID_SOURCE. This is also true for uClibc.

Alltogether, we can safely replace __USE_MISC by _GNU_SOURCE to support building
nodejs 0.10.x with the musl C library.

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>