package/qt5base: fix eglconvenience compile (missing QList include)
- add 0008-eglconvenience-add-missing-QList-include.patch to fix
  eglconvenience compile (missing QList include)

Fixes:

  qeglconvenience.cpp:418:23: error: variable ‘QList<QByteArray> extensions’ has initializer but incomplete type
    418 |     QList<QByteArray> extensions =
        |                       ^~~~~~~~~~
  qeglconvenience.cpp:420:65: error: invalid use of incomplete type ‘class QList<QByteArray>’
    420 |             (eglQueryString(display, EGL_EXTENSIONS))).split(' ');
        |                                                                 ^

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
(cherry picked from commit 68159373d1a1fcb542a1ad411141dc910b8e1d49)
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>