package/nodejs: fix legal info
Commit 07408779cc068041a2da6838fe077d1a679f1736 forgot to update hash of
LICENSE file (multiple components under MIT added:
https://github.com/nodejs/node/commit/71659fd4baa90006937e78d789ec0aef95672eb1
https://github.com/nodejs/node/commit/f17ce913c94d26c87a471179d99d8bc4134f7bb5)

ERROR: LICENSE has wrong sha256 hash:
ERROR: expected: b3a67885b5a6ac35e8bbe8190509e41b79b0d9a2e3fbd47186f2ac4727f63be5
ERROR: got     : 6211cc77f9ceaf365db12faf050775b3a1e6da7a1eff3577ba006c4918103c33

Fixes:
 - http://autobuild.buildroot.org/results/bd1e3238f294152d54ee8f5579431606309dbff3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>